name = "a-share-dashboard-scheduler"
main = "src/index.mjs"
compatibility_date = "2026-09-16"
preview_urls = false

[observability]
enabled = true

[observability.logs]
enabled = true

[triggers]
crons = [
  "25,40,55 1 * * MON-FRI",
  "10,25,40,55 2 * * MON-FRI",
  "10,25 3 * * MON-FRI",
  "5,20,35,50 5-6 * * MON-FRI",
  "5 7 * * MON-FRI"
]

