name = "a-share-dashboard-scheduler"
main = "src/index.mjs"
compatibility_date = "2026-09-16"

[triggers]
crons = [
  "25 1 * * 1-5",
  "30 2 * * 1-5",
  "5 5 * * 1-5",
  "30 6 * * 1-5",
  "5 7 * * 1-5"
]
